# Generated by Django 5.0 on 2024-11-04 14:27

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Название блока')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('it', models.IntegerField(blank=True, null=True, verbose_name='Нумерация')),
            ],
            options={
                'verbose_name': 'Добавить Блок',
                'verbose_name_plural': 'Добавить Блоки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория квартир',
                'verbose_name_plural': 'Категория квартир',
            },
        ),
        migrations.CreateModel(
            name='Osob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название особенности')),
            ],
            options={
                'verbose_name': 'Добавить Особенность',
                'verbose_name_plural': 'Добавить Особенности',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Сколько Комнат')),
                ('number', models.IntegerField(max_length=255, verbose_name='Сколько в виде цифры')),
            ],
            options={
                'verbose_name': 'Добавить Комнаты',
                'verbose_name_plural': 'Добавить Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Статус квартиры')),
                ('it', models.IntegerField(verbose_name='Id')),
            ],
            options={
                'verbose_name': 'Добавить Статус',
                'verbose_name_plural': 'Добавить Статус',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=0, verbose_name='этаж')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.block', verbose_name='Выбрать блок')),
            ],
            options={
                'verbose_name': 'Добавить Этаж',
                'verbose_name_plural': 'Добавить Этажи',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razmer', models.FloatField(verbose_name='Введите размер')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительная информация')),
                ('layote', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='layote/', verbose_name='Фотография планировки')),
                ('plan', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='plan/', verbose_name='Фотография на плане этажа')),
                ('object', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='object/', verbose_name='Фотография на объекте')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('exploitation', models.CharField(max_length=255, verbose_name='Ввод в эксплуатацию')),
                ('layout_text', models.CharField(max_length=255, verbose_name='Тип планировки')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('category', models.ManyToManyField(related_name='category_room', to='apartment.category', verbose_name='Выберите категорию')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_form', to='apartment.floor', verbose_name='Сколько этажей')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.rooms', verbose_name='Выберите количество комнат')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choise_room', to='apartment.status', verbose_name='Выберите статус')),
            ],
            options={
                'verbose_name': 'Добавить Квартиру',
                'verbose_name_plural': 'Добавить Квартиры',
            },
        ),
        migrations.CreateModel(
            name='ApartmentOsob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartmentosob', to='apartment.apartment')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osob', to='apartment.category')),
            ],
            options={
                'verbose_name': 'Добавить Особенности',
                'verbose_name_plural': 'Добавить Особенности',
                'unique_together': {('settings', 'title')},
            },
        ),
    ]
