# Generated by Django 5.0 on 2024-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.IntegerField(verbose_name='Сколько в виде цифры'),
        ),
    ]
